### ISSUE TITLE
look into alternative CI setup

### ISSUE THREAD

**Issue by njtierney** [njtierney/rmd4sci#14]
look at https://github.com/tidyverse/principles to see how they set this up with netlify to avoid adding the CNAME file into gh-pages every single time

**Comment by njtierney** [comment]
https://github.com/apreshill/badbook from @apreshill gives some great details on how to set this up

**Comment by apreshill** [comment]
haha 😭 badbook is me showing you how not to do it- it is a failing build :) If you are interested in piloting my instructions, can we do over email? alison@rstudio.com I *do* have tidyverse-approved workflows for bookdown + netlify, just working on the final write-ups.

Also see for working examples:
https://github.com/apreshill/bookdown-travis-branch-deploy
https://github.com/apreshill/bookdown-travis-production-context

**Comment by njtierney** [comment]
Oh right, I didn't read things properly! I skimmed over it and thought it was like:

> *slaps roof*

> "this badboy shows you how to spin up a book with CI"

**Comment by njtierney** [comment]
I'd love to pilot your instructions! But I probably won't look over this book until around March or so.

**Comment by njtierney** [comment]
Thanks to @apreshill 's help this now works!
